name: '🤖 Release Please'

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      website--release_created: ${{ steps.release-please.outputs.website--release_created }}
      website--sha: ${{ steps.release-please.outputs.website--sha }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please

  publish-website:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.website--release_created == 'true' }}
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'deploy-website.yml',
                ref: 'main',
                inputs: {
                  release-ref: "${{ needs.release-please.outputs.website--sha }}"
                },
              })
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
